name: rolling_text_example
description: Showcase app for the rolling_text Flutter package.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  rolling_text:
    path: ../
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
